# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_qr <- function(Xr, y) {
    .Call(`_tmax_lm_qr`, Xr, y)
}

max_t <- function(Xr, y) {
    .Call(`_tmax_max_t`, Xr, y)
}

max_t_mul_boot <- function(Xr, y, normmat, sandwich, nboot) {
    .Call(`_tmax_max_t_mul_boot`, Xr, y, normmat, sandwich, nboot)
}

max_t_mul_boot_by_k <- function(Xr, y, normmat, sandwich, nboot, ind_mat, individual_ = NULL) {
    .Call(`_tmax_max_t_mul_boot_by_k`, Xr, y, normmat, sandwich, nboot, ind_mat, individual_)
}

inverse_C <- function(xx, N) {
    .Call(`_tmax_inverse_C`, xx, N)
}

cov_mat_C <- function(Xr) {
    .Call(`_tmax_cov_mat_C`, Xr)
}

true_max_t <- function(xtx, Xr, y, beta_true, ind_mat) {
    .Call(`_tmax_true_max_t`, xtx, Xr, y, beta_true, ind_mat)
}

residual <- function(Xr, beta, y) {
    .Call(`_tmax_residual`, Xr, beta, y)
}

QR <- function(Xr) {
    .Call(`_tmax_QR`, Xr)
}

compute_qb <- function(Xr, tau, b) {
    .Call(`_tmax_compute_qb`, Xr, tau, b)
}

compute_b <- function(Xr, b) {
    .Call(`_tmax_compute_b`, Xr, b)
}

